package penjualan.view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import penjualan.implement.transaksiImplement;
import java.sql.SQLException;
import penjualan.koneksi.koneksi;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import penjualan.entity.barang;
import penjualan.entity.detailTransaksi;
import penjualan.entity.transaksi;
import penjualan.implement.detailTransaksiImplement;
import penjualan.interfc.detailTransaksiInterfc;
import penjualan.interfc.transaksiInterfc;
import siPenjualan.MenuPenjualan;

/**
 * @author Fadillah F
 */
public class TransaksiView extends javax.swing.JFrame {
    private DefaultTableModel model;
    transaksiInterfc trServis;
    detailTransaksiInterfc detServis;
    int row;
    
    public TransaksiView() throws SQLException{
        initComponents();
        model = new DefaultTableModel();
        trServis = new transaksiImplement();
        detServis = new detailTransaksiImplement();
        
        tabelTransaksi.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Subtotal");
        DateNow();
        genFak();
        setKodeBarang();
        setIdPelanggan();
    }
    
    private void setKodeBarang() throws SQLException {
        transaksiImplement getKdBrg = new transaksiImplement();
        ArrayList<String> urutanArr = getKdBrg.viewKdBrg();
        nama_barang.addItem("-=Pilih=-");
        for (Object o : urutanArr) {
            nama_barang.addItem((String) o);
        }
    }
    private void setIdPelanggan() throws SQLException {
        transaksiImplement getIdPlg = new transaksiImplement();
        ArrayList<String> urutanArr = getIdPlg.viewIdPlg();
        nama.addItem("-=Pilih=-");
        for (Object o: urutanArr) {
            nama.addItem ((String) o);
        }
    }
    
    private void DateNow() {
        Date tglJual = new Date();
        SimpleDateFormat formatTgl = new SimpleDateFormat("YYYY-MM-dd");
        String dmy = formatTgl.format(tglJual);
        tglPenjualan.setText(dmy);
    }
    
    public void genFak() {
        transaksiImplement getUrutan = new transaksiImplement();
        int urutan = getUrutan.urutanDb();
        Calendar now = Calendar.getInstance();
        String kode_awal = "PO";
        int year = now.get(Calendar.YEAR);
        int month = now.get(Calendar.MONTH);
        int day = now.get(Calendar.DAY_OF_MONTH);
        StringBuffer strValues = new StringBuffer();
        strValues.append(kode_awal);
        strValues.append("-");
        strValues.append(String.valueOf(year));
        strValues.append(String.valueOf(month));
        strValues.append(String.valueOf(day));
        strValues.append("-");
        strValues.append(String.valueOf(urutan));
        String result = strValues.toString();
        noFaktur.setText(result);
    }
    private void kosongkanData() {
        jumlah.setText("");
        harga.setText("");
        nama_barang.setSelectedItem("-=Pilih=-");
        stok.setText("");
    }
    
    private void kosongkanSemuaData() {
        nama.setSelectedItem("-=Pilih=-");
        alamat.setText("");
        notlp.setText("");
        jumlah.setText("");
        harga.setText("");
        nama_barang.setSelectedItem("-=Pilih=-");
        stok.setText("");
        genFak();
        model = new DefaultTableModel();
        tabelTransaksi.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Subtotal");
    }
    
    private void hitungTotalBayar() {
        int jmlRow = tabelTransaksi.getRowCount();
        int tot = 0;
        if (jmlRow == 0) {
            return;
        }else{
            for (int i = 0; i< jmlRow; i++) {
                int jmlTot = Integer.valueOf(String.valueOf(model.getValueAt(i,4)));
                tot += jmlTot;
            }
        }
        totalBayar.setText(String.valueOf(tot));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noFaktur = new javax.swing.JTextField();
        tglPenjualan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        notlp = new javax.swing.JTextField();
        nama = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        nama_barang = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        btnSimpanKeranjang = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpanTransaksi = new javax.swing.JButton();
        totalBayar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaksi Penjualan");

        jLabel2.setText("No. Faktur");

        noFaktur.setEditable(false);
        noFaktur.setEnabled(false);

        tglPenjualan.setEditable(false);
        tglPenjualan.setEnabled(false);

        jLabel3.setText("Tanggal Transaksi");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Data Pelanggan");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Data Barang");

        jLabel6.setText("Nama Pelanggan");

        jLabel7.setText("Alamat");

        jLabel8.setText("No Telp");

        alamat.setEditable(false);
        alamat.setColumns(20);
        alamat.setRows(3);
        alamat.setEnabled(false);
        jScrollPane1.setViewportView(alamat);

        notlp.setEditable(false);
        notlp.setEnabled(false);

        nama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namaItemStateChanged(evt);
            }
        });

        jLabel9.setText("Nama Barang");

        nama_barang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nama_barangItemStateChanged(evt);
            }
        });
        nama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_barangActionPerformed(evt);
            }
        });

        jLabel10.setText("Stok Barang");

        jLabel11.setText("Harga");

        jLabel12.setText("Jumlah Pembelian");

        stok.setEditable(false);
        stok.setEnabled(false);

        harga.setEditable(false);
        harga.setEnabled(false);

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Stok Barang", "Harga", "Jumlah pembelian"
            }
        ));
        jScrollPane2.setViewportView(tabelTransaksi);

        btnSimpanKeranjang.setText("Simpan Ke Keranjang");
        btnSimpanKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKeranjangActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        simpanTransaksi.setText("Simpan Transaksi");
        simpanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTransaksiActionPerformed(evt);
            }
        });

        totalBayar.setEditable(false);
        totalBayar.setEnabled(false);

        jLabel13.setText("Total Pembayaran");

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(53, 53, 53)
                                        .addComponent(noFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(tglPenjualan))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1)
                                            .addComponent(notlp, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nama_barang, 0, 166, Short.MAX_VALUE)
                                            .addComponent(harga)
                                            .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpanKeranjang)
                                .addGap(18, 18, 18)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanTransaksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(noFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tglPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel8)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSimpanKeranjang)
                                    .addComponent(hapus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(simpanTransaksi))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKeranjangActionPerformed
        String kode = (String) nama_barang.getSelectedItem();
        String kodeBarang = kode.substring(0, 5);
        String namaBarang = kode.substring(5, kode.length());
        int hrg = Integer.valueOf(harga.getText());
        int jml = Integer.valueOf(jumlah.getText());
        long subTot = hrg * jml;
        
        Object[] data = new Object[5];
        data[0] = kodeBarang;
        data[1] = namaBarang;
        data[2] = harga.getText();
        data[3] = jumlah.getText();
        data[4] = subTot;
        
        model.addRow(data);
        this.hitungTotalBayar();
        this.kosongkanData();
    }//GEN-LAST:event_btnSimpanKeranjangActionPerformed

    private void nama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_barangActionPerformed

    private void nama_barangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nama_barangItemStateChanged
        String kode = (String) nama_barang.getSelectedItem();
        String kodeFix = kode.substring(0, 5);
        try{
            Statement ktB = koneksi.getConnection().createStatement();
            ResultSet rsKBr = ktB.executeQuery("SELECT "
                    + "stok_barang, "
                    + "harga_barang "
                    + "FROM "
                    + "barang "
                    + "where "
                    + "kode_barang = '"
                    + kodeFix 
                    +"'");
            while (rsKBr.next()){
                stok.setText(rsKBr.getString("stok_barang").trim());
                harga.setText(rsKBr.getString("harga_barang").trim());
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_nama_barangItemStateChanged

    private void namaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namaItemStateChanged
        String kode = (String) nama.getSelectedItem();
        String kodeFix = kode.substring(0, 4);
        try{
            Statement ktB = koneksi.getConnection().createStatement();
            ResultSet rsKBr = ktB.executeQuery("SELECT "
                    + "alamat, "
                    + "notlp "
                    + "FROM pelanggan "
                    + "where id_pelanggan = '"
                    + kodeFix 
                    +"'");
            while (rsKBr.next()){
                alamat.setText(rsKBr.getString("alamat"));
                notlp.setText(rsKBr.getString("notlp"));
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_namaItemStateChanged

    private void simpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTransaksiActionPerformed
         try{
            transaksi tr = new  transaksi();
            String kode = (String)nama.getSelectedItem();
            String kodeFix = kode.substring(0,4);
            
            tr.setNoFaktur(noFaktur.getText());
            tr.setIdPelanggan(kodeFix);
            tr.setTglPenjualan(tglPenjualan.getText());

            trServis.insert(tr);
            
            int jmlRow = tabelTransaksi.getRowCount();
            int tot = 0;
            
             System.out.println("row " + jmlRow);
            if(jmlRow == 0 ){
                return;
            } else {
                for(int i = 0; i < jmlRow; i++){
                    String kdBarang = String.valueOf(model.getValueAt(i, 0));
                    int jmlBeli = Integer.valueOf(String.valueOf(model.getValueAt(i, 3)));
                    String subTotal = String.valueOf(model.getValueAt(i, 4));

                    detailTransaksi dtr = new detailTransaksi();
                    dtr.setKodeBarang(kdBarang);
                    dtr.setNoFaktur(noFaktur.getText());
                    dtr.setJumlah(jmlBeli);
                    dtr.setSubTotal(subTotal);
                    detServis.insert(dtr);
                }
            }
            JOptionPane.showMessageDialog(this, "Transaksi berhasil simpan");
            kosongkanSemuaData();
        }catch(SQLException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_simpanTransaksiActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int delData = tabelTransaksi.getSelectedRow();
        if (delData == -1){
            return;
        }else {
            model.removeRow(delData);
            this.hitungTotalBayar();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            new MenuPenjualan().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PelangganView.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    new TransaksiView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton btnSimpanKeranjang;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> nama;
    private javax.swing.JComboBox<String> nama_barang;
    private javax.swing.JTextField noFaktur;
    private javax.swing.JTextField notlp;
    private javax.swing.JButton simpanTransaksi;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTextField tglPenjualan;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables
}
